version: '3.8'
services:
  postgres.local:
    container_name: accounts-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: accounts-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  lra-coordinator.local:
    container_name: micro-tx
    image: container-registry.oracle.com/database/otmm:22.3
    hostname: localhost
    ports:
      - "8080:8080"
    environment:
      CONFIG_FILE: /app/config/tcs.yaml
    volumes:
      - ./:/app/config
    restart: unless-stopped

  account-service.local:
    build: .
    image: lra-example/account-service
    environment:
      DB_HOST: postgres.local
      DB_PORT: 5432
      COORDINATOR_URL: http://lra-coordinator.local:8080/api/v1/lra-coordinator
      PARTICIPANT_HOST: account-service.local
      PARTICIPANT_PORT: 8083
    ports:
      - "8083:8083"

volumes:
  postgres-data:
