server:
  port: 8080
  host: 0.0.0.0
  static.classpath:
    location: /WEB
    welcome: index.html

mp.lra:
  coordinator.url: ${COORDINATOR_URL}
  propagation.active: true
  participant.url: "http://${server.host}:${server.port}"

javax.sql.DataSource:
  accounts-db:
    dataSourceClassName: org.postgresql.ds.PGPoolingDataSource
    dataSource:
      serverName: ${DB_HOST}
      portNumber: ${DB_PORT}
      databaseName: accounts-db
      user: user
      password: pass